const MOVIES_DATABASE = [
  {
    id: 743563,
    title: 'Vikram',
    original_title: 'Vikram',
    language: 'Tamil',
    genres: ['Action', 'Thriller', 'Crime'],
    overview: 'A special agent investigates a series of violent crimes and discovers a conspiracy linking Chennai’s criminal underworld to a mysterious network.',
    cast: [{ name: 'Kamal Haasan', character: 'Agent Vikram / Karnan' }, { name: 'Vijay Sethupathi', character: 'Santanam' }, { name: 'Fahadh Faasil', character: 'Amar' }],
    director: 'Lokesh Kanagaraj',
    runtime: 175,
    release_date: '2022-06-03',
    vote_average: 8.3,
    vote_count: 14200,
    poster_path: 'https://image.tmdb.org/t/p/w500/ihjsoa6p8VEr0vIF95SZ0JBEbZ6.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg',
    keywords: ['undercover', 'drug cartel', 'crime thriller', 'chennai'],
    production_company: 'Raaj Kamal Films International',
    country: 'India',
    ott_providers: ['Disney+ Hotstar', 'ZEE5']
  },
  {
    id: 943722,
    title: 'Leo',
    original_title: 'Leo',
    language: 'Tamil',
    genres: ['Action', 'Thriller', 'Crime'],
    overview: 'A calm cafe owner is hunted by criminal syndicates after his hidden identity becomes exposed.',
    cast: [{ name: 'Vijay', character: 'Parthiban / Leo Das' }, { name: 'Sanjay Dutt', character: 'Antony Das' }, { name: 'Trisha Krishnan', character: 'Sathya' }],
    director: 'Lokesh Kanagaraj',
    runtime: 164,
    release_date: '2023-10-19',
    vote_average: 7.9,
    vote_count: 12500,
    poster_path: 'https://image.tmdb.org/t/p/w500/maBYHY7gSGGtqW9Ti8ZGVP0IAgg.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsX2f.jpg',
    keywords: ['gangster', 'mistaken identity', 'lcu', 'family'],
    production_company: 'Seven Screen Studio',
    country: 'India',
    ott_providers: ['Netflix']
  },
  {
    id: 615658,
    title: 'Master',
    original_title: 'Master',
    language: 'Tamil',
    genres: ['Action', 'Thriller', 'Drama'],
    overview: 'An alcoholic professor clashes with a ruthless gangster inside a juvenile school.',
    cast: [{ name: 'Vijay', character: 'JD' }, { name: 'Vijay Sethupathi', character: 'Bhavani' }],
    director: 'Lokesh Kanagaraj',
    runtime: 179,
    release_date: '2021-01-13',
    vote_average: 7.8,
    vote_count: 9800,
    poster_path: 'https://image.tmdb.org/t/p/w500/d8WJFQyNNAEmuGeDwxPhBpx0G4B.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nMKQueries0z9hM0C1a07.jpg',
    keywords: ['juvenile home', 'professor', 'gangster'],
    production_company: 'XB Film Creators',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 630566,
    title: 'Kaithi',
    original_title: 'Kaithi',
    language: 'Tamil',
    genres: ['Action', 'Thriller', 'Crime'],
    overview: 'A recently released prisoner drives a truck carrying injured police officers through a city under siege.',
    cast: [{ name: 'Karthi', character: 'Dilli' }, { name: 'Narain', character: 'Inspector Bejoy' }],
    director: 'Lokesh Kanagaraj',
    runtime: 145,
    release_date: '2019-10-25',
    vote_average: 8.5,
    vote_count: 11000,
    poster_path: 'https://image.tmdb.org/t/p/w500/2YvT3pdGngzpbAuxamTz4ZlabnT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/9uG1qBwAQHzabT324utaw9vFu2x.jpg',
    keywords: ['night chase', 'truck', 'crime thriller'],
    production_company: 'Dream Warrior Pictures',
    country: 'India',
    ott_providers: ['Disney+ Hotstar']
  },
  {
    id: 673593,
    title: 'Soorarai Pottru',
    original_title: 'Soorarai Pottru',
    language: 'Tamil',
    genres: ['Drama', 'Biography'],
    overview: 'A determined former pilot dreams of affordable air travel for everyone and challenges a corrupt industry.',
    cast: [{ name: 'Suriya', character: 'Maara' }, { name: 'Aparna Balamurali', character: 'Bommi' }],
    director: 'Sudha Kongara',
    runtime: 153,
    release_date: '2020-11-12',
    vote_average: 8.6,
    vote_count: 15400,
    poster_path: 'https://image.tmdb.org/t/p/w500/fbbj3viSUDEGT1fFFMNpHP1iUjw.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oSM2xSuIm.jpg',
    keywords: ['aviation', 'entrepreneur', 'inspiration'],
    production_company: '2D Entertainment',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 843241,
    title: 'Jai Bhim',
    original_title: 'Jai Bhim',
    language: 'Tamil',
    genres: ['Drama', 'Crime', 'Mystery'],
    overview: 'A lawyer fights a brutal system to seek justice for a tribal family trapped in a police conspiracy.',
    cast: [{ name: 'Suriya', character: 'Chandru' }, { name: 'Lijomol Jose', character: 'Senggeni' }],
    director: 'T. J. Gnanavel',
    runtime: 164,
    release_date: '2021-11-02',
    vote_average: 8.8,
    vote_count: 22000,
    poster_path: 'https://image.tmdb.org/t/p/w500/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/hZkgoQY85KGdfToZYellow.jpg',
    keywords: ['courtroom', 'human rights', 'police brutality'],
    production_company: '2D Entertainment',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 541135,
    title: 'Ratsasan',
    original_title: 'Ratsasan',
    language: 'Tamil',
    genres: ['Thriller', 'Crime', 'Mystery'],
    overview: 'An aspiring filmmaker turns into a detective and hunts a serial killer by studying psychology.',
    cast: [{ name: 'Vishnu Vishal', character: 'Arun' }, { name: 'Amala Paul', character: 'Viji' }],
    director: 'Ram Kumar',
    runtime: 170,
    release_date: '2018-10-05',
    vote_average: 8.7,
    vote_count: 18900,
    poster_path: 'https://image.tmdb.org/t/p/w500/49fh83Bh3HdhtSzRDM69CIqpRjK.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/qdIMYStW2YIf27xQVDEnIZ6yuvH.jpg',
    keywords: ['serial killer', 'psychological thriller'],
    production_company: 'Axess Film Factory',
    country: 'India',
    ott_providers: ['Disney+ Hotstar']
  },
  {
    id: 358485,
    title: 'Thani Oruvan',
    original_title: 'Thani Oruvan',
    language: 'Tamil',
    genres: ['Action', 'Thriller', 'Crime'],
    overview: 'An honest officer sets out to expose a genius scientist hiding behind a philanthropic empire.',
    cast: [{ name: 'Jayam Ravi', character: 'Nedumaaran' }, { name: 'Arvind Swamy', character: 'Madhusudhan' }],
    director: 'Moorthy',
    runtime: 145,
    release_date: '2015-08-28',
    vote_average: 8.4,
    vote_count: 8700,
    poster_path: 'https://image.tmdb.org/t/p/w500/1fsWqM2WCpW4I7ZRBQK6Jm1KZsU.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/1fsWqM2WCpW4I7ZRBQK6Jm1KZsU.jpg',
    keywords: ['cop thriller', 'scientist', 'corporate crime'],
    production_company: 'The Show People',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 614696,
    title: 'Asuran',
    original_title: 'Asuran',
    language: 'Tamil',
    genres: ['Action', 'Drama'],
    overview: 'A father is pulled into a long and violent fight for justice after a family tragedy.',
    cast: [{ name: 'Dhanush', character: 'Sivasaami' }, { name: 'Manju Warrier', character: 'Yasodha' }],
    director: 'Vetrimaaran',
    runtime: 141,
    release_date: '2019-10-04',
    vote_average: 8.5,
    vote_count: 9600,
    poster_path: 'https://image.tmdb.org/t/p/w500/lZPvLUMYEPLTE2df1VW5FHTYC8N.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/aS2aS3Wk2k04hY1.jpg',
    keywords: ['revenge', 'family feud', 'social drama'],
    production_company: 'V Creations',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 430598,
    title: 'Vada Chennai',
    original_title: 'Vada Chennai',
    language: 'Tamil',
    genres: ['Crime', 'Drama', 'Action'],
    overview: 'A young man from North Chennai rises inside a deadly criminal ecosystem.',
    cast: [{ name: 'Dhanush', character: 'Anbu' }, { name: 'Ameer', character: 'Madhav' }],
    director: 'Vetrimaaran',
    runtime: 164,
    release_date: '2018-10-17',
    vote_average: 8.6,
    vote_count: 9200,
    poster_path: 'https://image.tmdb.org/t/p/w500/S3BRZj3FJkYSvxco7pvPCUsQYK.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/vC2vC3Wk2k04hY1.jpg',
    keywords: ['gang war', 'north chennai', 'crime drama'],
    production_company: 'V Creations',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 1151538,
    title: 'Jailer',
    original_title: 'Jailer',
    language: 'Tamil',
    genres: ['Action', 'Comedy', 'Crime'],
    overview: 'A retired prison warden takes on a brutal gang to save his son.',
    cast: [{ name: 'Rajinikanth', character: 'Muthuvel Pandian' }, { name: 'Tamannaah Bhatia', character: 'Rathna' }],
    director: 'Nelson Dilipkumar',
    runtime: 168,
    release_date: '2023-08-10',
    vote_average: 7.7,
    vote_count: 9800,
    poster_path: 'https://image.tmdb.org/t/p/w500/8E1DJn1CQkJqlYx32IscYPm4qeT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/jL2jL3Wk2k04hY1.jpg',
    keywords: ['mass entertainer', 'prison', 'action comedy'],
    production_company: 'Sun Pictures',
    country: 'India',
    ott_providers: ['Netflix']
  },
  {
    id: 251508,
    title: 'Drishyam',
    original_title: 'Drishyam',
    language: 'Malayalam',
    genres: ['Crime', 'Drama', 'Thriller'],
    overview: 'A cable TV operator uses every trick he knows to protect his family after a tragic accident.',
    cast: [{ name: 'Mohanlal', character: 'Georgekutty' }, { name: 'Meena', character: 'Rani George' }],
    director: 'Jeethu Joseph',
    runtime: 160,
    release_date: '2013-12-19',
    vote_average: 8.6,
    vote_count: 24000,
    poster_path: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/tmU7GeKVZRiWBFaiOXWhIbVWeCh.jpg',
    keywords: ['alibi', 'family protection', 'perfect crime'],
    production_company: 'Aashirvad Cinemas',
    country: 'India',
    ott_providers: ['Disney+ Hotstar', 'Prime Video']
  },
  {
    id: 791986,
    title: 'Drishyam 2',
    original_title: 'Drishyam 2',
    language: 'Malayalam',
    genres: ['Crime', 'Drama', 'Thriller'],
    overview: 'The family is forced to relive the past when the case reopens with fresh evidence.',
    cast: [{ name: 'Mohanlal', character: 'Georgekutty' }, { name: 'Meena', character: 'Rani George' }],
    director: 'Jeethu Joseph',
    runtime: 140,
    release_date: '2021-02-19',
    vote_average: 8.5,
    vote_count: 18000,
    poster_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdTvaO5vba8UnfExhR9Ru8sAB4sHUvn_LXAaCS0dVgnKryqciel_GXat4&s=10',
    backdrop_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdTvaO5vba8UnfExhR9Ru8sAB4sHUvn_LXAaCS0dVgnKryqciel_GXat4&s=10',
    keywords: ['sequel', 'forensics', 'psychological thriller'],
    production_company: 'Aashirvad Cinemas',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 337626,
    title: 'Premam',
    original_title: 'Premam',
    language: 'Malayalam',
    genres: ['Romance', 'Comedy', 'Drama'],
    overview: 'A young man experiences love and heartbreak across three different phases of life.',
    cast: [{ name: 'Nivin Pauly', character: 'George' }, { name: 'Sai Pallavi', character: 'Malar' }],
    director: 'Alphonse Puthren',
    runtime: 156,
    release_date: '2015-05-29',
    vote_average: 8.4,
    vote_count: 16000,
    poster_path: 'https://m.media-amazon.com/images/M/MV5BNWJiMWMxYmMtNTQxMy00ZjE2LWEzYTAtNTdmODI4MGI4OTRlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    backdrop_path: 'https://m.media-amazon.com/images/M/MV5BNWJiMWMxYmMtNTQxMy00ZjE2LWEzYTAtNTdmODI4MGI4OTRlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    keywords: ['coming of age', 'romance', 'friendship'],
    production_company: 'Anwar Rasool',
    country: 'India',
    ott_providers: ['Disney+ Hotstar']
  },
  {
    id: 575510,
    title: 'Kumbalangi Nights',
    original_title: 'Kumbalangi Nights',
    language: 'Malayalam',
    genres: ['Drama', 'Romance', 'Comedy'],
    overview: 'The lives of four brothers in a coastal village are transformed by love and family conflict.',
    cast: [{ name: 'Shane Nigam', character: 'Saji' }, { name: 'Soubin Shahir', character: 'Bobby' }],
    director: 'Madhu C. Narayanan',
    runtime: 135,
    release_date: '2019-02-07',
    vote_average: 8.6,
    vote_count: 11000,
    poster_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlGAq9jCw7NdBX3qUHEUmtM8b6pf9u_Tcs00qiSlcZeNKl54YURdHFUGoMiJWheFTmBZAahQ&s=10',
    backdrop_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlGAq9jCw7NdBX3qUHEUmtM8b6pf9u_Tcs00qiSlcZeNKl54YURdHFUGoMiJWheFTmBZAahQ&s=10',
    keywords: ['family drama', 'coastal life', 'romance'],
    production_company: 'Yoodlee Films',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 1212073,
    title: 'Manjummel Boys',
    original_title: 'Manjummel Boys',
    language: 'Malayalam',
    genres: ['Adventure', 'Drama', 'Thriller'],
    overview: 'A group of friends attempt a daring rescue after one of them falls into a treacherous cave.',
    cast: [{ name: 'Soubin Shahir', character: 'Babu' }, { name: 'Sreenath Bhasi', character: 'Mallu' }],
    director: 'Chidambaram',
    runtime: 142,
    release_date: '2024-02-22',
    vote_average: 8.6,
    vote_count: 14000,
    poster_path: 'https://m.media-amazon.com/images/M/MV5BMDVkOGEzZDgtYWU4Yi00MDA3LWE4YmQtYjQxNDgwNDYxNGU4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    backdrop_path: 'https://m.media-amazon.com/images/M/MV5BMDVkOGEzZDgtYWU4Yi00MDA3LWE4YmQtYjQxNDgwNDYxNGU4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    keywords: ['cave rescue', 'adventure', 'friendship'],
    production_company: 'Parava Films',
    country: 'India',
    ott_providers: ['Prime Video']
  },
  {
    id: 579974,
    title: 'RRR',
    original_title: 'RRR',
    language: 'Telugu',
    genres: ['Action', 'Adventure', 'Drama'],
    overview: 'Two revolutionaries join forces to fight colonial oppression and change the course of history.',
    cast: [{ name: 'N. T. Rama Rao Jr.', character: 'Bheem' }, { name: 'Ram Charan', character: 'Alluri Sitarama Raju' }],
    director: 'S. S. Rajamouli',
    runtime: 187,
    release_date: '2022-03-24',
    vote_average: 8.2,
    vote_count: 19000,
    poster_path: 'https://image.tmdb.org/t/p/w500/nEufeZlyAODCndhyhyu3mwoWpA8.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/m9O9sU8Yd4ZcZzZ5z5z5z5z5z5z.jpg',
    keywords: ['revolution', 'friendship', 'massive action'],
    production_company: 'DVV Entertainment',
    country: 'India',
    ott_providers: ['Netflix', 'Prime Video']
  },
  {
    id: 360814,
    title: 'Dangal',
    original_title: 'Dangal',
    language: 'Hindi',
    genres: ['Drama', 'Biography', 'Action'],
    overview: 'A former wrestler guides his daughters on a journey that changes their lives and their country.',
    cast: [{ name: 'Aamir Khan', character: 'Mahavir Singh Phogat' }, { name: 'Fatima Sana Shaikh', character: 'Geeta Phogat' }],
    director: 'Nitesh Tiwari',
    runtime: 161,
    release_date: '2016-12-21',
    vote_average: 8.4,
    vote_count: 22000,
    poster_path: 'https://image.tmdb.org/t/p/w500/dG2dG3Wk2k04hY1.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/dG2dG3Wk2k04hY1.jpg',
    keywords: ['sports', 'family', 'inspiration'],
    production_company: 'Aamir Khan Productions',
    country: 'India',
    ott_providers: ['Netflix']
  },
  {
    id: 424694,
    title: 'Bohemian Rhapsody',
    original_title: 'Bohemian Rhapsody',
    language: 'English',
    genres: ['Drama', 'Music', 'Biography'],
    overview: 'The story of Freddie Mercury and the rise of Queen through global stardom and personal struggle.',
    cast: [{ name: 'Rami Malek', character: 'Freddie Mercury' }, { name: 'Lucy Boynton', character: 'Mary Austin' }],
    director: 'Bryan Singer',
    runtime: 134,
    release_date: '2018-10-24',
    vote_average: 8.0,
    vote_count: 18000,
    poster_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8zs4SGKEEADotfXmTBA1MJ-M9u0cbxPaP-1KA1_ukQXwPwrqur83dDztOmjiMhE5vD5ti&s=10',
    backdrop_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8zs4SGKEEADotfXmTBA1MJ-M9u0cbxPaP-1KA1_ukQXwPwrqur83dDztOmjiMhE5vD5ti&s=10',
    keywords: ['queen', 'music', 'biography'],
    production_company: '20th Century Fox',
    country: 'United States',
    ott_providers: ['Prime Video']
  },
  {
    id: 496243,
    title: 'Parasite',
    original_title: '기생충',
    language: 'Korean',
    genres: ['Comedy', 'Thriller', 'Drama'],
    overview: 'A poor family infiltrates the life of a wealthy household and becomes entangled in a dangerous web of secrets.',
    cast: [{ name: 'Song Kang-ho', character: 'Ki-taek' }, { name: 'Cho Yeo-jeong', character: 'Yeon-gyo' }],
    director: 'Bong Joon-ho',
    runtime: 132,
    release_date: '2019-05-30',
    vote_average: 8.5,
    vote_count: 42000,
    poster_path: 'https://image.tmdb.org/t/p/w500/7IiT2Z9qGi2uI7pG288e2.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/hiU37DHI3fry2O2Y4f5H0ZfWvmr.jpg',
    keywords: ['social satire', 'class struggle', 'thriller'],
    production_company: 'Barunson E&A',
    country: 'South Korea',
    ott_providers: ['Prime Video', 'SonyLIV']
  },
  {
    id: 296096,
    title: 'Train to Busan',
    original_title: '부산행',
    language: 'Korean',
    genres: ['Action', 'Horror', 'Thriller'],
    overview: 'A zombie outbreak turns a high-speed train ride into a desperate fight for survival.',
    cast: [{ name: 'Gong Yoo', character: 'Seok-woo' }, { name: 'Ma Dong-seok', character: 'Sang-hwa' }],
    director: 'Yeon Sang-ho',
    runtime: 118,
    release_date: '2016-07-20',
    vote_average: 7.8,
    vote_count: 28000,
    poster_path: 'https://m.media-amazon.com/images/M/MV5BMTkwOTQ4OTg0OV5BMl5BanBnXkFtZTgwMzQyOTM0OTE@._V1_.jpg',
    backdrop_path: 'https://m.media-amazon.com/images/M/MV5BMTkwOTQ4OTg0OV5BMl5BanBnXkFtZTgwMzQyOTM0OTE@._V1_.jpg',
    keywords: ['zombie', 'survival', 'action'],
    production_company: 'Next Entertainment World',
    country: 'South Korea',
    ott_providers: ['Netflix', 'Prime Video']
  },
  {
    id: 670,
    title: 'Oldboy',
    original_title: '올드보이',
    language: 'Korean',
    genres: ['Drama', 'Mystery', 'Thriller', 'Action'],
    overview: 'A man released after years of captivity has only five days to discover why he was imprisoned.',
    cast: [{ name: 'Choi Min-sik', character: 'Oh Dae-su' }, { name: 'Yoo Ji-tae', character: 'Lee Woo-jin' }],
    director: 'Park Chan-wook',
    runtime: 120,
    release_date: '2003-11-21',
    vote_average: 8.4,
    vote_count: 31000,
    poster_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1tLstZgjJLNVs1Mi2yPTEkT37KRsiZdby3ERH7I75Xvf_aN5IWqBVqACBIx9Yys1a2qv0&s=10',
    backdrop_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1tLstZgjJLNVs1Mi2yPTEkT37KRsiZdby3ERH7I75Xvf_aN5IWqBVqACBIx9Yys1a2qv0&s=10',
    keywords: ['revenge', 'mind-bending', 'mystery'],
    production_company: 'Show East',
    country: 'South Korea',
    ott_providers: ['Prime Video']
  },
  {
    id: 372058,
    title: 'Your Name.',
    original_title: '君の名は。',
    language: 'Japanese',
    genres: ['Animation', 'Romance', 'Drama', 'Fantasy'],
    overview: 'Two teenagers begin switching bodies across time and space and their lives become inseparably connected.',
    cast: [{ name: 'Ryunosuke Kamiki', character: 'Taki Tachibana' }, { name: 'Mone Kamishiraishi', character: 'Mitsuha Miyamizu' }],
    director: 'Makoto Shinkai',
    runtime: 106,
    release_date: '2016-08-26',
    vote_average: 8.5,
    vote_count: 38000,
    poster_path: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png',
    backdrop_path: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png',
    keywords: ['body swap', 'romance', 'anime masterpiece'],
    production_company: 'CoMix Wave Films',
    country: 'Japan',
    ott_providers: ['Netflix']
  },
  {
    id: 129,
    title: 'Spirited Away',
    original_title: '千と千尋の神隠し',
    language: 'Japanese',
    genres: ['Animation', 'Family', 'Fantasy'],
    overview: 'A young girl enters a magical world of spirits and must save her parents from a witch.',
    cast: [{ name: 'Rumi Hiiragi', character: 'Chihiro' }, { name: 'Miyu Irino', character: 'Haku' }],
    director: 'Hayao Miyazaki',
    runtime: 125,
    release_date: '2001-07-20',
    vote_average: 8.5,
    vote_count: 45000,
    poster_path: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png',
    backdrop_path: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png',
    keywords: ['studio ghibli', 'bathhouse', 'spirit world'],
    production_company: 'Studio Ghibli',
    country: 'Japan',
    ott_providers: ['Netflix']
  },
  {
    id: 27205,
    title: 'Inception',
    original_title: 'Inception',
    language: 'English',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    overview: 'A skilled thief enters people’s dreams to steal secrets and is offered a chance to plant an idea instead.',
    cast: [{ name: 'Leonardo DiCaprio', character: 'Dom Cobb' }, { name: 'Joseph Gordon-Levitt', character: 'Arthur' }],
    director: 'Christopher Nolan',
    runtime: 148,
    release_date: '2010-07-15',
    vote_average: 8.4,
    vote_count: 38000,
    poster_path: 'https://image.tmdb.org/t/p/w500/oYuLEW9W31i2s9CjveLflayStwU.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg',
    keywords: ['dreams', 'heist', 'mind-bending'],
    production_company: 'Warner Bros.',
    country: 'United States',
    ott_providers: ['Prime Video']
  },
  {
    id: 157336,
    title: 'Interstellar',
    original_title: 'Interstellar',
    language: 'English',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    overview: 'A group of explorers travels through a wormhole in search of a new home for humanity.',
    cast: [{ name: 'Matthew McConaughey', character: 'Cooper' }, { name: 'Anne Hathaway', character: 'Brand' }],
    director: 'Christopher Nolan',
    runtime: 169,
    release_date: '2014-11-05',
    vote_average: 8.4,
    vote_count: 36000,
    poster_path: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsX2f.jpg',
    keywords: ['space', 'time', 'humanity'],
    production_company: 'Paramount Pictures',
    country: 'United States',
    ott_providers: ['Prime Video']
  },
  {
    id: 155,
    title: 'The Dark Knight',
    original_title: 'The Dark Knight',
    language: 'English',
    genres: ['Action', 'Crime', 'Drama'],
    overview: 'Batman faces the Joker in a battle over Gotham’s soul.',
    cast: [{ name: 'Christian Bale', character: 'Bruce Wayne' }, { name: 'Heath Ledger', character: 'Joker' }],
    director: 'Christopher Nolan',
    runtime: 152,
    release_date: '2008-07-16',
    vote_average: 8.5,
    vote_count: 33000,
    poster_path: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nMKQueries0z9hM0C1a07.jpg',
    keywords: ['batman', 'crime', 'hero'],
    production_company: 'Warner Bros.',
    country: 'United States',
    ott_providers: ['Prime Video']
  }
];

module.exports = { MOVIES_DATABASE };